/**
 * Auto-generated resolver factory.
 *
 * Takes a ParsedSchema and ApiDependencies, produces a resolver map
 * matching the GraphQL schema generated by ODL codegen.
 *
 * Query resolvers (Section 8.1.1):
 *   foo(id)      → authenticate → authorise → get → redact → consent
 *   foos(filter) → authenticate → listObjects → query → redact → consent
 *
 * Mutation resolvers (Section 8.1.2):
 *   Each ActionType → ActionExecutor.execute
 *
 * Subscription resolvers (Section 8.1.4):
 *   fooChanged(id) → PubSub filter
 */

import type { ParsedSchema, ObjectType, ActionType, FieldDefinition } from '@openfoundry/odl';
import type { OntologyObject, FilterExpression, DataPurpose, AggregateQuery, AggregateField, AggregateFunction, SearchQuery } from '@openfoundry/spi';
import type { ActionActor, ActionContext } from '@openfoundry/actions';
import type { RedactionResult } from '@openfoundry/security';
import { PubSub } from 'graphql-subscriptions';
import type { ApiDependencies, ResolverContext, PaginationArgs } from './types.js';
import { DEFAULT_CONSENT_PURPOSE } from './types.js';
import { resolvePagination, buildConnection } from './pagination.js';
import { createOpenFoundryError, wrapError } from './errors.js';
import {
  createIdFilteredSubscription,
  createFilteredSubscription,
} from '../subscriptions/subscription-manager.js';

// ─── Helpers ───

function lowerFirst(s: string): string {
  return s.charAt(0).toLowerCase() + s.slice(1);
}

/** Convert PascalCase to snake_case — must match FGA codegen convention. */
function toSnakeCase(s: string): string {
  return s
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')
    .replace(/([a-z\d])([A-Z])/g, '$1_$2')
    .toLowerCase();
}

function isPrimaryField(field: FieldDefinition): boolean {
  return field.directives.some(d => d.kind === 'primary');
}

function isParamField(field: FieldDefinition): boolean {
  return field.directives.some(d => d.kind === 'param');
}

/**
 * Convert GraphQL filter input to SPI FilterExpression.
 * The GraphQL filter uses scalar filter inputs like { eq, ne, in, ... }.
 * We translate these to SPI FieldPredicate form.
 */
function convertFilter(filter: Record<string, unknown> | undefined): FilterExpression | undefined {
  if (!filter) return undefined;

  const predicates: FilterExpression[] = [];

  for (const [key, value] of Object.entries(filter)) {
    if (value == null) continue;

    if (key === 'AND' && Array.isArray(value)) {
      const subFilters = value.map((v: Record<string, unknown>) => convertFilter(v)).filter(Boolean) as FilterExpression[];
      if (subFilters.length > 0) {
        predicates.push({ and: subFilters });
      }
      continue;
    }
    if (key === 'OR' && Array.isArray(value)) {
      const subFilters = value.map((v: Record<string, unknown>) => convertFilter(v)).filter(Boolean) as FilterExpression[];
      if (subFilters.length > 0) {
        predicates.push({ or: subFilters });
      }
      continue;
    }
    if (key === 'NOT' && typeof value === 'object') {
      const sub = convertFilter(value as Record<string, unknown>);
      if (sub) predicates.push({ not: sub });
      continue;
    }

    // Scalar filter: { field: { eq: "x", gt: 5, ... } }
    if (typeof value === 'object' && !Array.isArray(value)) {
      const ops = value as Record<string, unknown>;
      for (const [op, opVal] of Object.entries(ops)) {
        if (opVal == null) continue;
        const spiOp = mapFilterOp(op);
        if (spiOp) {
          predicates.push({ field: key, operator: spiOp, value: opVal });
        }
      }
    }
  }

  if (predicates.length === 0) return undefined;
  if (predicates.length === 1) return predicates[0];
  return { and: predicates };
}

type SpiOperator = 'eq' | 'neq' | 'gt' | 'gte' | 'lt' | 'lte' | 'in' | 'contains' | 'startsWith' | 'exists';

function mapFilterOp(op: string): SpiOperator | undefined {
  const mapping: Record<string, SpiOperator> = {
    eq: 'eq',
    ne: 'neq',
    gt: 'gt',
    gte: 'gte',
    lt: 'lt',
    lte: 'lte',
    in: 'in',
    contains: 'contains',
    startsWith: 'startsWith',
  };
  return mapping[op];
}

/**
 * Convert GraphQL orderBy input to SPI QueryOptions.orderBy.
 */
function convertOrderBy(orderBy: Record<string, string> | undefined): { field: string; direction: 'asc' | 'desc' }[] | undefined {
  if (!orderBy) return undefined;
  const result: { field: string; direction: 'asc' | 'desc' }[] = [];
  for (const [field, dir] of Object.entries(orderBy)) {
    if (dir) {
      result.push({ field, direction: dir.toLowerCase() as 'asc' | 'desc' });
    }
  }
  return result.length > 0 ? result : undefined;
}

/**
 * Convert an OntologyObject to a GraphQL-friendly shape.
 * Strips the underscore prefix from system fields that map to schema fields.
 */
function objectToGraphQL(obj: OntologyObject, objectType: ObjectType): Record<string, unknown> {
  const result: Record<string, unknown> = {};

  for (const field of objectType.fields) {
    if (isPrimaryField(field)) {
      // Primary field (usually 'id') maps to _id
      result[field.name] = obj[`_${field.name}`] ?? obj[field.name];
    } else {
      result[field.name] = obj[field.name];
    }
  }

  // Include system metadata
  result._redactedFields = null;
  result._consentRestricted = false;

  return result;
}

// ─── Resolver map type ───

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type ResolverFn = (...args: any[]) => any;
type SubscriptionResolver = { subscribe: ResolverFn };
type ResolverValue = ResolverFn | SubscriptionResolver;
type ResolverMap = Record<string, Record<string, ResolverValue>>;

// ─── Public API ───

/**
 * Generate resolver map from ParsedSchema and dependencies.
 * Returns { resolvers, pubsub } where resolvers is the complete resolver map
 * and pubsub can be used to publish subscription events.
 */
export function generateResolvers(
  schema: ParsedSchema,
  deps: ApiDependencies,
): { resolvers: ResolverMap; pubsub: PubSub } {
  const pubsub = new PubSub();
  const resolvers: ResolverMap = {
    Query: {},
    Mutation: {},
    Subscription: {},
  };

  // Generate query resolvers for each ObjectType
  for (const obj of schema.objectTypes) {
    generateQueryResolvers(obj, resolvers, deps);
    generateAggregateResolver(obj, resolvers, deps);
    generateSearchResolver(obj, resolvers, deps);
    generateSubscriptionResolvers(obj, resolvers, pubsub);
  }

  // Generate mutation resolvers for each ActionType.
  // NOTE: Domain pack YAML action manifests are loaded at runtime via
  // ManifestRegistry but are NOT reflected in schema.actionTypes unless
  // the ODL schema includes @actionType directives. Until the schema
  // registry integrates pack manifest discovery, pack actions won't
  // appear as GraphQL/REST mutations automatically.
  for (const action of schema.actionTypes) {
    generateMutationResolver(action, schema, resolvers, deps, pubsub);
  }

  // availableTools query (Section 5.7)
  resolvers['Query']!['availableTools'] = generateAvailableToolsResolver(schema);

  // Object Set resolvers
  generateObjectSetResolvers(resolvers, deps);

  return { resolvers, pubsub };
}

// ─── Query resolvers ───

function generateQueryResolvers(
  obj: ObjectType,
  resolvers: ResolverMap,
  deps: ApiDependencies,
): void {
  const typeName = obj.name;
  const lower = lowerFirst(typeName);
  const fgaType = toSnakeCase(typeName);

  // Single object query: foo(id: ID!): Foo
  resolvers['Query']![lower] = async (
    _parent: unknown,
    args: { id: string },
    ctx: ResolverContext,
  ) => {
    try {
      // a. Authenticate (already done in context middleware)
      const { user, requestContext } = ctx;

      // b. Authorize: check user has viewer relation to this object
      const allowed = await deps.authorizationService.check(
        `user:${user.id}`,
        'viewer',
        `${fgaType}:${args.id}`,
      );
      if (!allowed) {
        throw createOpenFoundryError({
          code: 'FORBIDDEN',
          category: 'authorization',
          message: `Access denied to ${typeName} ${args.id}`,
          retryable: false,
          traceId: requestContext.traceId,
        });
      }

      // c. Get from engine
      const result = await deps.objectManager.get(typeName, args.id, requestContext);
      if (!result) {
        return null;
      }

      let gqlObj = objectToGraphQL(result, obj);

      // d. Field-level redaction
      const redacted = deps.authorizationService.redactFields(
        user.id,
        user.roles,
        typeName,
        gqlObj,
      );
      gqlObj = redacted.data as Record<string, unknown>;
      gqlObj._redactedFields = redacted._redactedFields.length > 0 ? redacted._redactedFields : null;

      // e. Consent filtering (single object)
      if (deps.consentService) {
        const consentResult = await deps.consentService.checkSingleObject(
          gqlObj,
          args.id,
          DEFAULT_CONSENT_PURPOSE as DataPurpose,
          user.id,
        );
        if (consentResult._consentRestricted) {
          gqlObj._consentRestricted = true;
          // Redact all non-primary fields for consent-restricted objects
          for (const field of obj.fields) {
            if (!isPrimaryField(field)) {
              gqlObj[field.name] = null;
            }
          }
        }
      }

      return gqlObj;
    } catch (err) {
      throw wrapError(err, ctx.requestContext.traceId);
    }
  };

  // List query: foos(filter, orderBy, first, after, last, before): FooConnection!
  resolvers['Query']![`${lower}s`] = async (
    _parent: unknown,
    args: { filter?: Record<string, unknown>; orderBy?: Record<string, string> } & PaginationArgs,
    ctx: ResolverContext,
  ) => {
    try {
      const { user, requestContext } = ctx;

      // a. Authenticate (already done in context)

      // b. Authorization: list objects user can see
      const allowedObjects = await deps.authorizationService.listObjects(
        `user:${user.id}`,
        'viewer',
        fgaType,
      );

      // Build filter: combine user filter with authorization filter
      const userFilter = convertFilter(args.filter);

      // Extract IDs from authorization results (format: "type:id")
      const allowedIds = allowedObjects.map((o: string) => {
        const parts = o.split(':');
        return parts[parts.length - 1];
      }).filter((id): id is string => id !== undefined && id !== '');

      // SEC-11: If no objects are authorized, return empty connection immediately
      if (allowedIds.length === 0) {
        return buildConnection([], 0, 0);
      }

      // Build combined filter
      let combinedFilter: FilterExpression;
      const idFilter: FilterExpression = {
        field: '_id',
        operator: 'in',
        value: allowedIds,
      };

      if (userFilter) {
        combinedFilter = { and: [idFilter, userFilter] };
      } else {
        combinedFilter = idFilter;
      }

      // c. Resolve pagination
      const { offset, limit } = resolvePagination(args);

      // d. Query engine
      const page = await deps.objectManager.query(
        typeName,
        combinedFilter,
        {
          limit,
          offset,
          orderBy: convertOrderBy(args.orderBy),
        },
        requestContext,
      );

      // e. Apply field-level redaction to all items
      const redactedItems = deps.authorizationService.redactFieldsBatch(
        user.id,
        user.roles,
        typeName,
        page.items.map((item: OntologyObject) => objectToGraphQL(item, obj)),
      );

      let items = redactedItems.map((r: RedactionResult<Record<string, unknown>>) => {
        const data = r.data as Record<string, unknown>;
        data._redactedFields = r._redactedFields.length > 0 ? r._redactedFields : null;
        data._consentRestricted = false;
        return data;
      });

      // f. Consent filtering (applied after pagination — see FHIR router for details)
      let totalCount = page.totalCount;
      if (deps.consentService) {
        const getPrimaryId = (item: Record<string, unknown>) => {
          const primaryField = obj.fields.find(f => isPrimaryField(f));
          return String(item[primaryField?.name ?? 'id'] ?? '');
        };
        const consentResult = await deps.consentService.filterList(
          items,
          getPrimaryId,
          DEFAULT_CONSENT_PURPOSE as DataPurpose,
          user.id,
        );
        items = consentResult.edges;
        totalCount = consentResult.totalCount;
      }

      // g. Build Relay connection
      return buildConnection(items, totalCount, offset);
    } catch (err) {
      throw wrapError(err, ctx.requestContext.traceId);
    }
  };
}

// ─── Auth helper ───

/**
 * Resolve authorized object IDs for a user+type via FGA listObjects.
 * Returns the list of allowed IDs (empty array if none authorized).
 */
async function resolveAllowedIds(
  deps: ApiDependencies,
  userId: string,
  fgaType: string,
): Promise<string[]> {
  const allowedObjects = await deps.authorizationService.listObjects(
    `user:${userId}`,
    'viewer',
    fgaType,
  );
  return allowedObjects.map((o: string) => {
    const parts = o.split(':');
    return parts[parts.length - 1];
  }).filter((id): id is string => id !== undefined && id !== '');
}

/**
 * Build a combined filter that restricts to authorized IDs + optional user filter.
 */
function buildAuthFilter(
  allowedIds: string[],
  userFilter?: FilterExpression,
): FilterExpression {
  const idFilter: FilterExpression = {
    field: '_id',
    operator: 'in',
    value: allowedIds,
  };
  return userFilter ? { and: [idFilter, userFilter] } : idFilter;
}

// ─── Aggregate resolvers ───

function generateAggregateResolver(
  obj: ObjectType,
  resolvers: ResolverMap,
  deps: ApiDependencies,
): void {
  const typeName = obj.name;
  const lower = lowerFirst(typeName);
  const fgaType = toSnakeCase(typeName);

  // fooAggregate(filter, groupBy, fields): AggregateResult!
  resolvers['Query']![`${lower}Aggregate`] = async (
    _parent: unknown,
    args: {
      filter?: Record<string, unknown>;
      groupBy?: string[];
      fields: Array<{ field: string; fn: string; alias?: string }>;
    },
    ctx: ResolverContext,
  ) => {
    try {
      const { user, requestContext } = ctx;

      // Authorization: restrict aggregation to authorized objects
      const allowedIds = await resolveAllowedIds(deps, user.id, fgaType);
      if (allowedIds.length === 0) {
        return { groups: [], totalGroups: 0 };
      }

      // Convert GraphQL filter to SPI filter and combine with auth filter
      const userFilter = convertFilter(args.filter);
      const combinedFilter = buildAuthFilter(allowedIds, userFilter);

      // Convert GraphQL aggregate fields to SPI AggregateField[]
      const fields: AggregateField[] = args.fields.map((f) => ({
        field: f.field,
        fn: f.fn.toLowerCase() as AggregateFunction,
        alias: f.alias,
      }));

      const query: AggregateQuery = {
        fields,
        groupBy: args.groupBy,
        filter: combinedFilter,
      };

      return deps.objectManager.aggregate(typeName, query, requestContext);
    } catch (err) {
      throw wrapError(err, ctx.requestContext.traceId);
    }
  };
}

// ─── Search resolvers ───

function generateSearchResolver(
  obj: ObjectType,
  resolvers: ResolverMap,
  deps: ApiDependencies,
): void {
  const typeName = obj.name;
  const fgaType = toSnakeCase(typeName);

  // searchFoos(query, fields, filter, first, after): SearchResult_Foo!
  resolvers['Query']![`search${typeName}s`] = async (
    _parent: unknown,
    args: {
      query: string;
      fields?: string[];
      filter?: Record<string, unknown>;
      first?: number;
      after?: string;
    },
    ctx: ResolverContext,
  ) => {
    try {
      const { user, requestContext } = ctx;

      // Reject empty search queries
      if (!args.query || args.query.trim().length === 0) {
        throw createOpenFoundryError({
          code: 'INVALID_ARGUMENT',
          category: 'validation',
          message: 'Search query must not be empty',
          retryable: false,
          traceId: requestContext.traceId,
        });
      }

      // Authorization: restrict search to authorized objects
      const allowedIds = await resolveAllowedIds(deps, user.id, fgaType);
      if (allowedIds.length === 0) {
        return { hits: [], totalCount: 0, hasNextPage: false };
      }

      // Convert GraphQL filter to SPI filter and combine with auth filter
      const userFilter = convertFilter(args.filter);
      const combinedFilter = buildAuthFilter(allowedIds, userFilter);

      // Resolve pagination: 'after' is an opaque cursor encoding an offset
      let offset = 0;
      if (args.after) {
        const decoded = parseInt(Buffer.from(args.after, 'base64').toString('utf8'), 10);
        if (!isNaN(decoded)) {
          offset = decoded;
        }
      }

      const searchQuery: SearchQuery = {
        query: args.query,
        fields: args.fields,
        filter: combinedFilter,
        limit: args.first ?? 20,
        offset,
      };

      const result = await deps.objectManager.search(typeName, searchQuery, requestContext);

      // Map hits to GraphQL shape with field-level redaction
      const rawItems = result.hits.map((hit) => objectToGraphQL(hit.object, obj));
      const redactedItems = deps.authorizationService.redactFieldsBatch(
        user.id,
        user.roles,
        typeName,
        rawItems,
      );

      let hits = redactedItems.map((r: RedactionResult<Record<string, unknown>>, i: number) => {
        const data = r.data as Record<string, unknown>;
        data._redactedFields = r._redactedFields.length > 0 ? r._redactedFields : null;
        data._consentRestricted = false;
        return { node: data, score: result.hits[i]!.score };
      });

      // Consent filtering
      let totalCount = result.totalCount;
      if (deps.consentService) {
        const getPrimaryId = (hit: { node: Record<string, unknown>; score: number }) => {
          const primaryField = obj.fields.find(f => isPrimaryField(f));
          return String(hit.node[primaryField?.name ?? 'id'] ?? '');
        };
        const consentResult = await deps.consentService.filterList(
          hits,
          getPrimaryId,
          DEFAULT_CONSENT_PURPOSE as DataPurpose,
          user.id,
        );
        hits = consentResult.edges;
        totalCount = consentResult.totalCount;
      }

      return {
        hits,
        totalCount,
        hasNextPage: result.hasNextPage,
      };
    } catch (err) {
      throw wrapError(err, ctx.requestContext.traceId);
    }
  };
}

// ─── Mutation resolvers ───

function generateMutationResolver(
  action: ActionType,
  schema: ParsedSchema,
  resolvers: ResolverMap,
  deps: ApiDependencies,
  pubsub: PubSub,
): void {
  const fieldName = lowerFirst(action.name);

  resolvers['Mutation']![fieldName] = async (
    _parent: unknown,
    args: { input: Record<string, unknown> },
    ctx: ResolverContext,
  ) => {
    try {
      const { user, requestContext } = ctx;

      // Build ActionActor from authenticated user
      const actor: ActionActor = {
        id: user.id,
        type: 'user',
        roles: user.roles,
      };

      // Build ActionContext
      const actionCtx: ActionContext = {
        requestContext,
      };

      // Resolve manifest from registry — fail closed if not found
      const manifest = deps.manifestRegistry?.get(action.name);
      if (!manifest) {
        return {
          success: false,
          actionId: `err_${Date.now().toString(36)}`,
          errors: [{ code: 'MANIFEST_NOT_FOUND', message: `No manifest registered for action "${action.name}"` }],
          affectedObjects: [],
        };
      }

      // Execute via ActionExecutor
      const result = await deps.actionExecutor.execute(
        manifest,
        args.input,
        actor,
        actionCtx,
        schema,
      );

      // Publish change events for subscriptions
      for (const affected of result.affectedObjects) {
        const topic = `${lowerFirst(affected.type)}Changed`;
        // CQ-18: Log errors from pubsub publish instead of silently swallowing
        pubsub.publish(topic, {
          [topic]: {
            changeType: affected.changeType.toUpperCase(),
            object: { id: affected.id, _type: affected.type },
            previousValues: null,
            causedBy: action.name,
            timestamp: new Date().toISOString(),
          },
        }).catch((err: unknown) => {
          console.warn(`[PubSub] Failed to publish to ${topic}:`, err instanceof Error ? err.message : String(err));
        });
      }

      return {
        success: result.success,
        actionId: result.actionId,
        errors: result.errors.length > 0 ? result.errors : null,
        affectedObjects: result.affectedObjects.map(o => ({
          typeName: o.type,
          id: o.id,
          changeType: o.changeType.toUpperCase(),
        })),
      };
    } catch (err) {
      throw wrapError(err, ctx.requestContext.traceId);
    }
  };
}

// ─── Subscription resolvers ───

function generateSubscriptionResolvers(
  obj: ObjectType,
  resolvers: ResolverMap,
  pubsub: PubSub,
): void {
  const lower = lowerFirst(obj.name);
  const topic = `${lower}Changed`;

  // fooChanged(id: ID!) — subscribe to changes on a specific object
  resolvers['Subscription']![topic] = createIdFilteredSubscription(pubsub, topic);

  // foosChanged(filter: FooFilter) — subscribe to all changes on a type
  resolvers['Subscription']![`${lower}sChanged`] = createFilteredSubscription(pubsub, topic);
}

// ─── availableTools resolver (Section 5.7) ───

function generateAvailableToolsResolver(
  schema: ParsedSchema,
): (_parent: unknown, args: { filter?: { kind?: string; tags?: string[] } }, _ctx: ResolverContext) => unknown[] {
  // Pre-build tool descriptors from action types
  const tools = schema.actionTypes.map((action) => {
    // Build JSON Schema for parameters from @param fields
    const paramFields = action.fields.filter(isParamField);
    const properties: Record<string, unknown> = {};
    const required: string[] = [];

    for (const field of paramFields) {
      properties[field.name] = {
        type: mapOdlTypeToJsonSchema(field.type.name),
        description: field.description ?? field.name,
      };
      if (field.type.nonNull) {
        required.push(field.name);
      }
    }

    const parameters = {
      type: 'object',
      properties,
      required: required.length > 0 ? required : undefined,
    };

    const returnType = {
      type: 'object',
      properties: {
        success: { type: 'boolean' },
        actionId: { type: 'string' },
        errors: { type: 'array', items: { type: 'object' } },
        affectedObjects: { type: 'array', items: { type: 'object' } },
      },
    };

    return {
      name: action.name,
      kind: 'ACTION',
      description: action.description ?? `Execute ${action.name} action`,
      parameters,
      returnType,
      requiredPermissions: [`action:${action.name}`],
      dryRunSupported: false,
      reversible: false,
      tags: [] as string[],
    };
  });

  return (_parent, args) => {
    let filtered = tools;

    if (args.filter?.kind) {
      filtered = filtered.filter(t => t.kind === args.filter!.kind);
    }
    if (args.filter?.tags && args.filter.tags.length > 0) {
      const filterTags = new Set(args.filter.tags);
      filtered = filtered.filter(t => t.tags.some((tag: string) => filterTags.has(tag)));
    }

    return filtered;
  };
}

// ─── Object Set resolvers ───

function generateObjectSetResolvers(
  resolvers: ResolverMap,
  deps: ApiDependencies,
): void {
  // Query: objectSet(id: ID!): ObjectSet
  resolvers['Query']!['objectSet'] = async (
    _parent: unknown,
    args: { id: string },
    ctx: ResolverContext,
  ) => {
    try {
      if (!deps.objectSetManager) return null;
      const def = await deps.objectSetManager.get(args.id, ctx.requestContext);
      return def ? objectSetToGraphQL(def) : null;
    } catch (err) {
      throw wrapError(err, ctx.requestContext.traceId);
    }
  };

  // Query: objectSets(objectType: String): [ObjectSet!]!
  resolvers['Query']!['objectSets'] = async (
    _parent: unknown,
    args: { objectType?: string },
    ctx: ResolverContext,
  ) => {
    try {
      if (!deps.objectSetManager) return [];
      const defs = await deps.objectSetManager.list(args.objectType, ctx.requestContext);
      return defs.map(objectSetToGraphQL);
    } catch (err) {
      throw wrapError(err, ctx.requestContext.traceId);
    }
  };

  // Mutation: createObjectSet(input: CreateObjectSetInput!): ObjectSet!
  resolvers['Mutation']!['createObjectSet'] = async (
    _parent: unknown,
    args: { input: Record<string, unknown> },
    ctx: ResolverContext,
  ) => {
    try {
      if (!deps.objectSetManager) {
        throw createOpenFoundryError({
          code: 'NOT_CONFIGURED',
          category: 'system',
          message: 'Object set manager is not configured',
          retryable: false,
          traceId: ctx.requestContext.traceId,
        });
      }
      const def = await deps.objectSetManager.create(
        {
          name: args.input['name'] as string,
          description: args.input['description'] as string | undefined,
          objectType: args.input['objectType'] as string,
          filter: args.input['filter'] as undefined,
          orderBy: args.input['orderBy'] as undefined,
          limit: args.input['limit'] as number | undefined,
          isPublic: (args.input['isPublic'] as boolean) ?? false,
          createdBy: ctx.user.id,
          tenantId: ctx.requestContext.tenantId,
        },
        ctx.requestContext,
      );
      return objectSetToGraphQL(def);
    } catch (err) {
      throw wrapError(err, ctx.requestContext.traceId);
    }
  };

  // Mutation: updateObjectSet(id: ID!, input: UpdateObjectSetInput!): ObjectSet!
  resolvers['Mutation']!['updateObjectSet'] = async (
    _parent: unknown,
    args: { id: string; input: Record<string, unknown> },
    ctx: ResolverContext,
  ) => {
    try {
      if (!deps.objectSetManager) {
        throw createOpenFoundryError({
          code: 'NOT_CONFIGURED',
          category: 'system',
          message: 'Object set manager is not configured',
          retryable: false,
          traceId: ctx.requestContext.traceId,
        });
      }
      const updates: Record<string, unknown> = {};
      for (const [key, value] of Object.entries(args.input)) {
        if (value !== undefined) {
          updates[key] = value;
        }
      }
      const def = await deps.objectSetManager.update(args.id, updates, ctx.requestContext);
      return objectSetToGraphQL(def);
    } catch (err) {
      throw wrapError(err, ctx.requestContext.traceId);
    }
  };

  // Mutation: deleteObjectSet(id: ID!): Boolean!
  resolvers['Mutation']!['deleteObjectSet'] = async (
    _parent: unknown,
    args: { id: string },
    ctx: ResolverContext,
  ) => {
    try {
      if (!deps.objectSetManager) {
        throw createOpenFoundryError({
          code: 'NOT_CONFIGURED',
          category: 'system',
          message: 'Object set manager is not configured',
          retryable: false,
          traceId: ctx.requestContext.traceId,
        });
      }
      await deps.objectSetManager.delete(args.id, ctx.requestContext);
      return true;
    } catch (err) {
      throw wrapError(err, ctx.requestContext.traceId);
    }
  };
}

function objectSetToGraphQL(def: {
  id: string;
  name: string;
  description?: string;
  objectType: string;
  filter?: unknown;
  orderBy?: unknown;
  limit?: number;
  isPublic: boolean;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}): Record<string, unknown> {
  return {
    id: def.id,
    name: def.name,
    description: def.description ?? null,
    objectType: def.objectType,
    filter: def.filter ?? null,
    orderBy: def.orderBy ?? null,
    limit: def.limit ?? null,
    isPublic: def.isPublic,
    createdBy: def.createdBy,
    createdAt: def.createdAt,
    updatedAt: def.updatedAt,
  };
}

function mapOdlTypeToJsonSchema(typeName: string): string {
  const mapping: Record<string, string> = {
    ID: 'string',
    String: 'string',
    Int: 'integer',
    Float: 'number',
    Boolean: 'boolean',
    Date: 'string',
    DateTime: 'string',
    Duration: 'string',
    JSON: 'object',
    URI: 'string',
  };
  return mapping[typeName] ?? 'string';
}
