// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: cel_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CelEvaluator_Evaluate_FullMethodName      = "/cel.CelEvaluator/Evaluate"
	CelEvaluator_EvaluateBatch_FullMethodName = "/cel.CelEvaluator/EvaluateBatch"
)

// CelEvaluatorClient is the client API for CelEvaluator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CelEvaluator provides CEL expression evaluation as a gRPC service.
// Per Open Foundry Spec v2 Section 5.2.4, CEL runtime evaluation MUST use
// a canonical evaluator. This Go sidecar is the authoritative runtime.
type CelEvaluatorClient interface {
	// Evaluate a single CEL expression.
	Evaluate(ctx context.Context, in *EvalRequest, opts ...grpc.CallOption) (*EvalResponse, error)
	// Evaluate multiple CEL expressions in a single round-trip.
	// Reduces gRPC overhead when actions have multiple preconditions/effects.
	EvaluateBatch(ctx context.Context, in *BatchEvalRequest, opts ...grpc.CallOption) (*BatchEvalResponse, error)
}

type celEvaluatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCelEvaluatorClient(cc grpc.ClientConnInterface) CelEvaluatorClient {
	return &celEvaluatorClient{cc}
}

func (c *celEvaluatorClient) Evaluate(ctx context.Context, in *EvalRequest, opts ...grpc.CallOption) (*EvalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvalResponse)
	err := c.cc.Invoke(ctx, CelEvaluator_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *celEvaluatorClient) EvaluateBatch(ctx context.Context, in *BatchEvalRequest, opts ...grpc.CallOption) (*BatchEvalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchEvalResponse)
	err := c.cc.Invoke(ctx, CelEvaluator_EvaluateBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CelEvaluatorServer is the server API for CelEvaluator service.
// All implementations must embed UnimplementedCelEvaluatorServer
// for forward compatibility.
//
// CelEvaluator provides CEL expression evaluation as a gRPC service.
// Per Open Foundry Spec v2 Section 5.2.4, CEL runtime evaluation MUST use
// a canonical evaluator. This Go sidecar is the authoritative runtime.
type CelEvaluatorServer interface {
	// Evaluate a single CEL expression.
	Evaluate(context.Context, *EvalRequest) (*EvalResponse, error)
	// Evaluate multiple CEL expressions in a single round-trip.
	// Reduces gRPC overhead when actions have multiple preconditions/effects.
	EvaluateBatch(context.Context, *BatchEvalRequest) (*BatchEvalResponse, error)
	mustEmbedUnimplementedCelEvaluatorServer()
}

// UnimplementedCelEvaluatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCelEvaluatorServer struct{}

func (UnimplementedCelEvaluatorServer) Evaluate(context.Context, *EvalRequest) (*EvalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedCelEvaluatorServer) EvaluateBatch(context.Context, *BatchEvalRequest) (*BatchEvalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateBatch not implemented")
}
func (UnimplementedCelEvaluatorServer) mustEmbedUnimplementedCelEvaluatorServer() {}
func (UnimplementedCelEvaluatorServer) testEmbeddedByValue()                      {}

// UnsafeCelEvaluatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CelEvaluatorServer will
// result in compilation errors.
type UnsafeCelEvaluatorServer interface {
	mustEmbedUnimplementedCelEvaluatorServer()
}

func RegisterCelEvaluatorServer(s grpc.ServiceRegistrar, srv CelEvaluatorServer) {
	// If the following call panics, it indicates UnimplementedCelEvaluatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CelEvaluator_ServiceDesc, srv)
}

func _CelEvaluator_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CelEvaluatorServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CelEvaluator_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CelEvaluatorServer).Evaluate(ctx, req.(*EvalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CelEvaluator_EvaluateBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchEvalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CelEvaluatorServer).EvaluateBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CelEvaluator_EvaluateBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CelEvaluatorServer).EvaluateBatch(ctx, req.(*BatchEvalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CelEvaluator_ServiceDesc is the grpc.ServiceDesc for CelEvaluator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CelEvaluator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cel.CelEvaluator",
	HandlerType: (*CelEvaluatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Evaluate",
			Handler:    _CelEvaluator_Evaluate_Handler,
		},
		{
			MethodName: "EvaluateBatch",
			Handler:    _CelEvaluator_EvaluateBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cel_service.proto",
}
