// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: cel_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TypeEntry describes a variable's type for the CEL type environment.
type TypeEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CelType       string                 `protobuf:"bytes,2,opt,name=cel_type,json=celType,proto3" json:"cel_type,omitempty"` // e.g. "string", "int", "bool", "double",
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeEntry) Reset() {
	*x = TypeEntry{}
	mi := &file_cel_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeEntry) ProtoMessage() {}

func (x *TypeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cel_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeEntry.ProtoReflect.Descriptor instead.
func (*TypeEntry) Descriptor() ([]byte, []int) {
	return file_cel_service_proto_rawDescGZIP(), []int{0}
}

func (x *TypeEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TypeEntry) GetCelType() string {
	if x != nil {
		return x.CelType
	}
	return ""
}

// TypeEnv declares the types of all variables available in a CEL expression.
type TypeEnv struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*TypeEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeEnv) Reset() {
	*x = TypeEnv{}
	mi := &file_cel_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeEnv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeEnv) ProtoMessage() {}

func (x *TypeEnv) ProtoReflect() protoreflect.Message {
	mi := &file_cel_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeEnv.ProtoReflect.Descriptor instead.
func (*TypeEnv) Descriptor() ([]byte, []int) {
	return file_cel_service_proto_rawDescGZIP(), []int{1}
}

func (x *TypeEnv) GetEntries() []*TypeEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// EvalRequest is a single CEL evaluation request.
type EvalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The CEL expression to evaluate.
	Expression string `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	// Variables available to the expression, keyed by name.
	// Values use google.protobuf.Value for dynamic typing.
	Variables map[string]*structpb.Value `protobuf:"bytes,2,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Type declarations for variables so CEL can type-check.
	TypeEnv       *TypeEnv `protobuf:"bytes,3,opt,name=type_env,json=typeEnv,proto3" json:"type_env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalRequest) Reset() {
	*x = EvalRequest{}
	mi := &file_cel_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalRequest) ProtoMessage() {}

func (x *EvalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cel_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalRequest.ProtoReflect.Descriptor instead.
func (*EvalRequest) Descriptor() ([]byte, []int) {
	return file_cel_service_proto_rawDescGZIP(), []int{2}
}

func (x *EvalRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *EvalRequest) GetVariables() map[string]*structpb.Value {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *EvalRequest) GetTypeEnv() *TypeEnv {
	if x != nil {
		return x.TypeEnv
	}
	return nil
}

// EvalResponse is the result of a single CEL evaluation.
type EvalResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The result of evaluating the expression.
	Result *structpb.Value `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// Non-empty if evaluation failed.
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalResponse) Reset() {
	*x = EvalResponse{}
	mi := &file_cel_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalResponse) ProtoMessage() {}

func (x *EvalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cel_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalResponse.ProtoReflect.Descriptor instead.
func (*EvalResponse) Descriptor() ([]byte, []int) {
	return file_cel_service_proto_rawDescGZIP(), []int{3}
}

func (x *EvalResponse) GetResult() *structpb.Value {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *EvalResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// BatchEvalRequest evaluates multiple expressions against the same variable set.
type BatchEvalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Expressions to evaluate.
	Expressions []string `protobuf:"bytes,1,rep,name=expressions,proto3" json:"expressions,omitempty"`
	// Shared variables for all expressions.
	Variables map[string]*structpb.Value `protobuf:"bytes,2,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Shared type environment.
	TypeEnv       *TypeEnv `protobuf:"bytes,3,opt,name=type_env,json=typeEnv,proto3" json:"type_env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchEvalRequest) Reset() {
	*x = BatchEvalRequest{}
	mi := &file_cel_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEvalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEvalRequest) ProtoMessage() {}

func (x *BatchEvalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cel_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEvalRequest.ProtoReflect.Descriptor instead.
func (*BatchEvalRequest) Descriptor() ([]byte, []int) {
	return file_cel_service_proto_rawDescGZIP(), []int{4}
}

func (x *BatchEvalRequest) GetExpressions() []string {
	if x != nil {
		return x.Expressions
	}
	return nil
}

func (x *BatchEvalRequest) GetVariables() map[string]*structpb.Value {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *BatchEvalRequest) GetTypeEnv() *TypeEnv {
	if x != nil {
		return x.TypeEnv
	}
	return nil
}

// BatchEvalResult is the result of one expression in a batch.
type BatchEvalResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expression    string                 `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	Result        *structpb.Value        `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchEvalResult) Reset() {
	*x = BatchEvalResult{}
	mi := &file_cel_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEvalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEvalResult) ProtoMessage() {}

func (x *BatchEvalResult) ProtoReflect() protoreflect.Message {
	mi := &file_cel_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEvalResult.ProtoReflect.Descriptor instead.
func (*BatchEvalResult) Descriptor() ([]byte, []int) {
	return file_cel_service_proto_rawDescGZIP(), []int{5}
}

func (x *BatchEvalResult) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *BatchEvalResult) GetResult() *structpb.Value {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *BatchEvalResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// BatchEvalResponse contains results for all expressions in a batch.
type BatchEvalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*BatchEvalResult     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchEvalResponse) Reset() {
	*x = BatchEvalResponse{}
	mi := &file_cel_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEvalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEvalResponse) ProtoMessage() {}

func (x *BatchEvalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cel_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEvalResponse.ProtoReflect.Descriptor instead.
func (*BatchEvalResponse) Descriptor() ([]byte, []int) {
	return file_cel_service_proto_rawDescGZIP(), []int{6}
}

func (x *BatchEvalResponse) GetResults() []*BatchEvalResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_cel_service_proto protoreflect.FileDescriptor

const file_cel_service_proto_rawDesc = "" +
	"\n" +
	"\x11cel_service.proto\x12\x03cel\x1a\x1cgoogle/protobuf/struct.proto\":\n" +
	"\tTypeEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bcel_type\x18\x02 \x01(\tR\acelType\"3\n" +
	"\aTypeEnv\x12(\n" +
	"\aentries\x18\x01 \x03(\v2\x0e.cel.TypeEntryR\aentries\"\xeb\x01\n" +
	"\vEvalRequest\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\x12=\n" +
	"\tvariables\x18\x02 \x03(\v2\x1f.cel.EvalRequest.VariablesEntryR\tvariables\x12'\n" +
	"\btype_env\x18\x03 \x01(\v2\f.cel.TypeEnvR\atypeEnv\x1aT\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"T\n" +
	"\fEvalResponse\x12.\n" +
	"\x06result\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xf7\x01\n" +
	"\x10BatchEvalRequest\x12 \n" +
	"\vexpressions\x18\x01 \x03(\tR\vexpressions\x12B\n" +
	"\tvariables\x18\x02 \x03(\v2$.cel.BatchEvalRequest.VariablesEntryR\tvariables\x12'\n" +
	"\btype_env\x18\x03 \x01(\v2\f.cel.TypeEnvR\atypeEnv\x1aT\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"w\n" +
	"\x0fBatchEvalResult\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\x12.\n" +
	"\x06result\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x06result\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"C\n" +
	"\x11BatchEvalResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.cel.BatchEvalResultR\aresults2\x7f\n" +
	"\fCelEvaluator\x12/\n" +
	"\bEvaluate\x12\x10.cel.EvalRequest\x1a\x11.cel.EvalResponse\x12>\n" +
	"\rEvaluateBatch\x12\x15.cel.BatchEvalRequest\x1a\x16.cel.BatchEvalResponseB,Z*github.com/openfoundry/cel-evaluator/protob\x06proto3"

var (
	file_cel_service_proto_rawDescOnce sync.Once
	file_cel_service_proto_rawDescData []byte
)

func file_cel_service_proto_rawDescGZIP() []byte {
	file_cel_service_proto_rawDescOnce.Do(func() {
		file_cel_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cel_service_proto_rawDesc), len(file_cel_service_proto_rawDesc)))
	})
	return file_cel_service_proto_rawDescData
}

var file_cel_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cel_service_proto_goTypes = []any{
	(*TypeEntry)(nil),         // 0: cel.TypeEntry
	(*TypeEnv)(nil),           // 1: cel.TypeEnv
	(*EvalRequest)(nil),       // 2: cel.EvalRequest
	(*EvalResponse)(nil),      // 3: cel.EvalResponse
	(*BatchEvalRequest)(nil),  // 4: cel.BatchEvalRequest
	(*BatchEvalResult)(nil),   // 5: cel.BatchEvalResult
	(*BatchEvalResponse)(nil), // 6: cel.BatchEvalResponse
	nil,                       // 7: cel.EvalRequest.VariablesEntry
	nil,                       // 8: cel.BatchEvalRequest.VariablesEntry
	(*structpb.Value)(nil),    // 9: google.protobuf.Value
}
var file_cel_service_proto_depIdxs = []int32{
	0,  // 0: cel.TypeEnv.entries:type_name -> cel.TypeEntry
	7,  // 1: cel.EvalRequest.variables:type_name -> cel.EvalRequest.VariablesEntry
	1,  // 2: cel.EvalRequest.type_env:type_name -> cel.TypeEnv
	9,  // 3: cel.EvalResponse.result:type_name -> google.protobuf.Value
	8,  // 4: cel.BatchEvalRequest.variables:type_name -> cel.BatchEvalRequest.VariablesEntry
	1,  // 5: cel.BatchEvalRequest.type_env:type_name -> cel.TypeEnv
	9,  // 6: cel.BatchEvalResult.result:type_name -> google.protobuf.Value
	5,  // 7: cel.BatchEvalResponse.results:type_name -> cel.BatchEvalResult
	9,  // 8: cel.EvalRequest.VariablesEntry.value:type_name -> google.protobuf.Value
	9,  // 9: cel.BatchEvalRequest.VariablesEntry.value:type_name -> google.protobuf.Value
	2,  // 10: cel.CelEvaluator.Evaluate:input_type -> cel.EvalRequest
	4,  // 11: cel.CelEvaluator.EvaluateBatch:input_type -> cel.BatchEvalRequest
	3,  // 12: cel.CelEvaluator.Evaluate:output_type -> cel.EvalResponse
	6,  // 13: cel.CelEvaluator.EvaluateBatch:output_type -> cel.BatchEvalResponse
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_cel_service_proto_init() }
func file_cel_service_proto_init() {
	if File_cel_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cel_service_proto_rawDesc), len(file_cel_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cel_service_proto_goTypes,
		DependencyIndexes: file_cel_service_proto_depIdxs,
		MessageInfos:      file_cel_service_proto_msgTypes,
	}.Build()
	File_cel_service_proto = out.File
	file_cel_service_proto_goTypes = nil
	file_cel_service_proto_depIdxs = nil
}
