/**
 * SQL (PostgreSQL) output formatter for seed data.
 *
 * Generates INSERT statements matching the nhs-acute schema.
 * Uses multi-row VALUES for performance.
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import type { SeedData } from './types.js';

const BATCH_SIZE = 500;

function esc(value: string | null | undefined): string {
  if (value === null || value === undefined) return 'NULL';
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlBatches(
  table: string,
  columns: string[],
  rows: string[][],
): string {
  const lines: string[] = [];
  for (let i = 0; i < rows.length; i += BATCH_SIZE) {
    const batch = rows.slice(i, i + BATCH_SIZE);
    const colList = columns.join(', ');
    const values = batch
      .map(row => `  (${row.join(', ')})`)
      .join(',\n');
    lines.push(`INSERT INTO ${table} (${colList}) VALUES\n${values};\n`);
  }
  return lines.join('\n');
}

export function writeSql(data: SeedData, outputDir: string): string {
  mkdirSync(outputDir, { recursive: true });
  const path = resolve(outputDir, 'seed.sql');

  const sections: string[] = [
    '-- NHS Acute Synthetic Seed Data',
    '-- Generated by @openfoundry/seed-nhs-acute',
    `-- ${new Date().toISOString()}`,
    '',
    'BEGIN;',
    '',
  ];

  // Wards
  sections.push(sqlBatches(
    'wards',
    ['id', 'name', 'specialty', 'capacity'],
    data.wards.map(w => [esc(w.id), esc(w.name), esc(w.specialty), String(w.capacity)]),
  ));

  // Beds
  sections.push(sqlBatches(
    'beds',
    ['id', 'number', 'type', 'status'],
    data.beds.map(b => [esc(b.id), esc(b.number), esc(b.type), esc(b.status)]),
  ));

  // Consultants
  sections.push(sqlBatches(
    'consultants',
    ['id', 'gmc_number', 'name', 'specialty'],
    data.consultants.map(c => [esc(c.id), esc(c.gmcNumber), esc(c.name), esc(c.specialty)]),
  ));

  // Patients
  sections.push(sqlBatches(
    'patients',
    ['id', 'nhs_number', 'name', 'date_of_birth', 'status', 'triage_category'],
    data.patients.map(p => [
      esc(p.id), esc(p.nhsNumber), esc(p.name), esc(p.dateOfBirth),
      esc(p.status), esc(p.triageCategory),
    ]),
  ));

  // Discharge records
  sections.push(sqlBatches(
    'discharge_records',
    ['id', 'patient', 'ward', 'destination', 'discharge_date', 'notes'],
    data.dischargeRecords.map(d => [
      esc(d.id), esc(d.patientId), esc(d.wardId), esc(d.destination),
      esc(d.dischargeDate), esc(d.notes),
    ]),
  ));

  // Links: BedInWard
  sections.push(sqlBatches(
    'bed_in_ward',
    ['id', 'from_id', 'to_id'],
    data.links.bedInWard.map(l => [esc(l.id), esc(l.fromId), esc(l.toId)]),
  ));

  // Links: AdmittedTo
  sections.push(sqlBatches(
    'admitted_to',
    ['id', 'from_id', 'to_id', 'admission_date', 'expected_discharge', 'reason'],
    data.links.admittedTo.map(l => [
      esc(l.id), esc(l.fromId), esc(l.toId), esc(l.admissionDate),
      esc(l.expectedDischarge), esc(l.reason),
    ]),
  ));

  // Links: OccupiesBed
  sections.push(sqlBatches(
    'occupies_bed',
    ['id', 'from_id', 'to_id', 'assigned_at'],
    data.links.occupiesBed.map(l => [esc(l.id), esc(l.fromId), esc(l.toId), esc(l.assignedAt)]),
  ));

  // Links: UnderCareOf
  sections.push(sqlBatches(
    'under_care_of',
    ['id', 'from_id', 'to_id', 'assigned_date', 'role'],
    data.links.underCareOf.map(l => [
      esc(l.id), esc(l.fromId), esc(l.toId), esc(l.assignedDate), esc(l.role),
    ]),
  ));

  sections.push('COMMIT;', '');

  const sql = sections.join('\n');
  writeFileSync(path, sql);
  return path;
}
