apiVersion: v1
kind: Service
metadata:
  name: {{ include "openfoundry.fullname" . }}-action-executor
  labels:
    {{- include "openfoundry.labels" . | nindent 4 }}
    app.kubernetes.io/component: action-executor
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.actionExecutor.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openfoundry.selectorLabels" (dict "name" "action-executor" "release" .Release.Name) | nindent 4 }}
