apiVersion: v1
kind: Service
metadata:
  name: {{ include "openfoundry.fullname" . }}-api-gateway
  labels:
    {{- include "openfoundry.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.apiGateway.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openfoundry.selectorLabels" (dict "name" "api-gateway" "release" .Release.Name) | nindent 4 }}
