apiVersion: v1
kind: Service
metadata:
  name: {{ include "openfoundry.fullname" . }}-cel-evaluator
  labels:
    {{- include "openfoundry.labels" . | nindent 4 }}
    app.kubernetes.io/component: cel-evaluator
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.celEvaluatorService.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "openfoundry.selectorLabels" (dict "name" "cel-evaluator" "release" .Release.Name) | nindent 4 }}
