apiVersion: v1
kind: Service
metadata:
  name: {{ include "openfoundry.fullname" . }}-ontology-engine
  labels:
    {{- include "openfoundry.labels" . | nindent 4 }}
    app.kubernetes.io/component: ontology-engine
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ontologyEngine.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openfoundry.selectorLabels" (dict "name" "ontology-engine" "release" .Release.Name) | nindent 4 }}
