/**
 * PostgreSQL implementation of the ConsentStore interface.
 *
 * Stores consent records in "consent"."consent_records" and
 * national data opt-outs in "consent"."opt_outs".
 * DDL generated by ddl-consent.ts during applySchema.
 *
 * Records are ordered by seq DESC (BIGSERIAL) to guarantee
 * newest-first ordering regardless of timestamp collisions.
 */

import type { Pool } from 'pg';
import type { ConsentRecord } from '@openfoundry/spi';

/**
 * ConsentStore interface — structurally compatible with
 * @openfoundry/security ConsentStore without requiring a direct import.
 */
export interface ConsentStoreInterface {
  put(record: ConsentRecord, tenantId?: string): Promise<void>;
  getBySubject(subjectId: string, tenantId?: string): Promise<ConsentRecord[]>;
  hasOptOut(subjectId: string, tenantId?: string): Promise<boolean>;
  setOptOut(subjectId: string, optedOut: boolean, tenantId?: string): Promise<void>;
}

export class PostgresConsentStore implements ConsentStoreInterface {
  private readonly pool: Pool;
  private readonly tenantId: string;

  /**
   * @param pool — pg Pool
   * @param tenantId — tenant scope for all consent queries (default: 'default')
   */
  constructor(pool: Pool, tenantId = 'default') {
    this.pool = pool;
    this.tenantId = tenantId;
  }

  /**
   * Store a consent record.
   */
  async put(record: ConsentRecord, tenantId?: string): Promise<void> {
    const tid = tenantId ?? this.tenantId;
    await this.pool.query(
      `INSERT INTO "consent"."consent_records"
        ("tenant_id", "subject_id", "purpose", "decision", "granted_at", "evidence")
       VALUES ($1, $2, $3, $4, $5, $6)`,
      [
        tid,
        record.subjectId,
        record.purpose,
        record.decision,
        record.grantedAt,
        record.evidence ?? null,
      ],
    );
  }

  /**
   * Retrieve all consent records for a subject, ordered by insertion
   * order (most recent first). The ConsentService relies on this ordering
   * to find the latest decision for a (subject, purpose) pair.
   */
  async getBySubject(subjectId: string, tenantId?: string): Promise<ConsentRecord[]> {
    const tid = tenantId ?? this.tenantId;
    const result = await this.pool.query(
      `SELECT "subject_id", "purpose", "decision", "granted_at", "evidence"
       FROM "consent"."consent_records"
       WHERE "tenant_id" = $1 AND "subject_id" = $2
       ORDER BY "seq" ASC`,
      [tid, subjectId],
    );
    return result.rows.map(rowToConsentRecord);
  }

  /**
   * Check if a subject has opted out (National Data Opt-Out).
   */
  async hasOptOut(subjectId: string, tenantId?: string): Promise<boolean> {
    const tid = tenantId ?? this.tenantId;
    const result = await this.pool.query(
      `SELECT 1 FROM "consent"."opt_outs" WHERE "tenant_id" = $1 AND "subject_id" = $2`,
      [tid, subjectId],
    );
    return result.rows.length > 0;
  }

  /**
   * Record or remove a national data opt-out for a subject.
   */
  async setOptOut(subjectId: string, optedOut: boolean, tenantId?: string): Promise<void> {
    const tid = tenantId ?? this.tenantId;
    if (optedOut) {
      await this.pool.query(
        `INSERT INTO "consent"."opt_outs" ("tenant_id", "subject_id") VALUES ($1, $2)
         ON CONFLICT ("tenant_id", "subject_id") DO NOTHING`,
        [tid, subjectId],
      );
    } else {
      await this.pool.query(
        `DELETE FROM "consent"."opt_outs" WHERE "tenant_id" = $1 AND "subject_id" = $2`,
        [tid, subjectId],
      );
    }
  }
}

function rowToConsentRecord(row: Record<string, unknown>): ConsentRecord {
  return {
    subjectId: row['subject_id'] as string,
    purpose: row['purpose'] as ConsentRecord['purpose'],
    decision: row['decision'] as ConsentRecord['decision'],
    grantedAt: row['granted_at'] instanceof Date
      ? (row['granted_at'] as Date).toISOString()
      : row['granted_at'] as string,
    evidence: row['evidence'] as string | undefined,
  };
}
