/**
 * PostgreSQL implementation of the AuditStore interface.
 *
 * Stores immutable audit records in the "audit"."audit_records" table
 * (DDL generated by ddl-audit.ts during applySchema).
 *
 * This implementation:
 * - Inserts records as single-row INSERTs (no batching, audit is low-volume)
 * - Queries with parameterized WHERE clauses for each filter field
 * - Orders by timestamp DESC by default
 * - Uses JSONB for the detail column (before/after state snapshots)
 */

import type { Pool } from 'pg';
import type { AuditRecord, AuditActor, AuditOperation, AuditDetail } from '@openfoundry/spi';

// ---------------------------------------------------------------------------
// Filter type (structurally compatible with @openfoundry/security AuditQueryFilter)
// ---------------------------------------------------------------------------

export interface AuditQueryFilter {
  actorId?: string;
  actorType?: 'user' | 'system' | 'connector';
  objectType?: string;
  objectId?: string;
  actionType?: string;
  operationType?: 'read' | 'create' | 'update' | 'delete' | 'action' | 'query' | 'link' | 'unlink';
  traceId?: string;
  from?: string;
  to?: string;
}

// ---------------------------------------------------------------------------
// Implementation
// ---------------------------------------------------------------------------

export class PostgresAuditStore {
  private readonly pool: Pool;

  constructor(pool: Pool) {
    this.pool = pool;
  }

  /**
   * Append an audit record to the store.
   * Records are immutable — no updates or deletes are ever performed.
   */
  async append(record: AuditRecord): Promise<void> {
    const detail: AuditDetail = record.detail;

    await this.pool.query(
      `INSERT INTO "audit"."audit_records"
        ("id", "timestamp", "trace_id",
         "actor_type", "actor_id", "actor_roles", "actor_ip",
         "op_type", "op_object_type", "op_object_id", "op_action_type", "op_action_id",
         "detail")
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)`,
      [
        record.id,
        record.timestamp,
        record.traceId,
        record.actor.type,
        record.actor.id,
        record.actor.roles,
        record.actor.ip ?? null,
        record.operation.type,
        record.operation.objectType ?? null,
        record.operation.objectId ?? null,
        record.operation.actionType ?? null,
        record.operation.actionId ?? null,
        JSON.stringify(detail),
      ],
    );
  }

  /**
   * Query audit records matching the given filter.
   * Returns records ordered by timestamp descending (most recent first).
   */
  async query(filter: AuditQueryFilter): Promise<AuditRecord[]> {
    const conditions: string[] = [];
    const params: unknown[] = [];
    let paramIdx = 1;

    if (filter.actorId !== undefined) {
      conditions.push(`"actor_id" = $${paramIdx++}`);
      params.push(filter.actorId);
    }
    if (filter.actorType !== undefined) {
      conditions.push(`"actor_type" = $${paramIdx++}`);
      params.push(filter.actorType);
    }
    if (filter.objectType !== undefined) {
      conditions.push(`"op_object_type" = $${paramIdx++}`);
      params.push(filter.objectType);
    }
    if (filter.objectId !== undefined) {
      conditions.push(`"op_object_id" = $${paramIdx++}`);
      params.push(filter.objectId);
    }
    if (filter.actionType !== undefined) {
      conditions.push(`"op_action_type" = $${paramIdx++}`);
      params.push(filter.actionType);
    }
    if (filter.operationType !== undefined) {
      conditions.push(`"op_type" = $${paramIdx++}`);
      params.push(filter.operationType);
    }
    if (filter.traceId !== undefined) {
      conditions.push(`"trace_id" = $${paramIdx++}`);
      params.push(filter.traceId);
    }
    if (filter.from !== undefined) {
      conditions.push(`"timestamp" >= $${paramIdx++}`);
      params.push(filter.from);
    }
    if (filter.to !== undefined) {
      conditions.push(`"timestamp" <= $${paramIdx++}`);
      params.push(filter.to);
    }

    const where = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : '';
    const sql = `SELECT * FROM "audit"."audit_records" ${where} ORDER BY "timestamp" DESC LIMIT 1000`;

    const result = await this.pool.query(sql, params);
    return result.rows.map(rowToAuditRecord);
  }
}

// ---------------------------------------------------------------------------
// Row mapping
// ---------------------------------------------------------------------------

function rowToAuditRecord(row: Record<string, unknown>): AuditRecord {
  const actor: AuditActor = {
    type: row['actor_type'] as AuditActor['type'],
    id: row['actor_id'] as string,
    roles: (row['actor_roles'] as string[]) ?? [],
  };
  if (row['actor_ip']) {
    actor.ip = row['actor_ip'] as string;
  }

  const operation: AuditOperation = {
    type: row['op_type'] as AuditOperation['type'],
  };
  if (row['op_object_type']) operation.objectType = row['op_object_type'] as string;
  if (row['op_object_id']) operation.objectId = row['op_object_id'] as string;
  if (row['op_action_type']) operation.actionType = row['op_action_type'] as string;
  if (row['op_action_id']) operation.actionId = row['op_action_id'] as string;

  const detail = (row['detail'] ?? {}) as AuditDetail;

  return {
    id: row['id'] as string,
    timestamp: (row['timestamp'] as Date).toISOString(),
    traceId: row['trace_id'] as string,
    actor,
    operation,
    detail,
  };
}
