# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ner.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'ner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tner.proto\x12\x06ner.v1\"w\n\x0e\x45xtractRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06labels\x18\x02 \x03(\t\x12\x16\n\x0emin_confidence\x18\x03 \x01(\x02\x12\x14\n\x0cmax_entities\x18\x04 \x01(\x05\x12\x19\n\x11\x65nable_llm_review\x18\x05 \x01(\x08\"_\n\x0f\x45xtractResponse\x12 \n\x08\x65ntities\x18\x01 \x03(\x0b\x32\x0e.ner.v1.Entity\x12*\n\x08metadata\x18\x02 \x01(\x0b\x32\x18.ner.v1.PipelineMetadata\"o\n\x06\x45ntity\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x0f\n\x07\x63ontext\x18\x04 \x01(\t\x12$\n\x06status\x18\x05 \x01(\x0e\x32\x14.ner.v1.EntityStatus\"\xf9\x01\n\x10PipelineMetadata\x12\x14\n\x0cgliner_count\x18\x01 \x01(\x05\x12\x13\n\x0b\x66lair_count\x18\x02 \x01(\x05\x12\x11\n\tconflicts\x18\x03 \x01(\x05\x12\x14\n\x0cllm_reviewed\x18\x04 \x01(\x05\x12\x13\n\x0b\x66inal_count\x18\x05 \x01(\x05\x12\x19\n\x11stage1_latency_ms\x18\x06 \x01(\x02\x12\x19\n\x11stage3_latency_ms\x18\x07 \x01(\x02\x12\x13\n\x0bllm_invoked\x18\x08 \x01(\x08\x12\x18\n\x10gliner_available\x18\t \x01(\x08\x12\x17\n\x0f\x66lair_available\x18\n \x01(\x08*\xad\x02\n\x0c\x45ntityStatus\x12\x1d\n\x19\x45NTITY_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n\x17\x45NTITY_STATUS_CONFIRMED\x10\x01\x12\x1f\n\x1b\x45NTITY_STATUS_SINGLE_SOURCE\x10\x02\x12!\n\x1d\x45NTITY_STATUS_GLINER_ENRICHED\x10\x03\x12\x1a\n\x16\x45NTITY_STATUS_CONFLICT\x10\x04\x12\x1e\n\x1a\x45NTITY_STATUS_LLM_VERIFIED\x10\x05\x12\x1f\n\x1b\x45NTITY_STATUS_LLM_CORRECTED\x10\x06\x12\x1b\n\x17\x45NTITY_STATUS_LLM_ADDED\x10\x07\x12#\n\x1f\x45NTITY_STATUS_CONFLICT_RESOLVED\x10\x08\x32P\n\nNerService\x12\x42\n\x0f\x45xtractEntities\x12\x16.ner.v1.ExtractRequest\x1a\x17.ner.v1.ExtractResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENTITYSTATUS']._serialized_start=605
  _globals['_ENTITYSTATUS']._serialized_end=906
  _globals['_EXTRACTREQUEST']._serialized_start=21
  _globals['_EXTRACTREQUEST']._serialized_end=140
  _globals['_EXTRACTRESPONSE']._serialized_start=142
  _globals['_EXTRACTRESPONSE']._serialized_end=237
  _globals['_ENTITY']._serialized_start=239
  _globals['_ENTITY']._serialized_end=350
  _globals['_PIPELINEMETADATA']._serialized_start=353
  _globals['_PIPELINEMETADATA']._serialized_end=602
  _globals['_NERSERVICE']._serialized_start=908
  _globals['_NERSERVICE']._serialized_end=988
# @@protoc_insertion_point(module_scope)
